version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build-frontend:
    docker:
      - image: cimg/node:22.12
    steps:
      - checkout
      - run:
          name: Install frontend dependencies
          command: npm install --ignore-scripts
      - run:
          name: Build frontend
          command: npm run build

  build-backend:
    docker:
      - image: cimg/node:22.12
    steps:
      - checkout
      - run:
          name: Install build tools
          command: sudo apt-get update && sudo apt-get install -y python3 make g++
