version: 2.1

jobs:
  build-frontend:
    docker:
      - image: cimg/node:22.12
    steps:
      - checkout
      - run:
          name: Install frontend dependencies
          command: npm install --ignore-scripts
      - run:
          name: Build frontend
          command: npm run build

  build-backend:
    docker:
      - image: cimg/node:22.12
    steps:
      - checkout
      - run:
          name: Install build tools
          command: sudo apt-get update && sudo apt-get install -y python3 make g++
      - run:
          name: Install backend dependencies
          command: cd backend && npm install

  sonarcloud-scan:
    docker:
      - image: cimg/node:22.12
    steps:
      - checkout
      - run:
          name: Install Sonar Scanner
          command: npm install sonarqube-scanner
      - run:
          name: Run SonarCloud Scan
          command: |
            npx sonar-scanner \
              -Dsonar.projectKey=Theelucy_APDS-GROUP-PROJECT \
              -Dsonar.organization=theelucy \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  build-and-test:
    jobs:
      - build-frontend
      - build-backend
      - sonarcloud-scan
